# fly.toml app configuration file generated for backend-ambikira on 2023-08-23T21:09:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-ambikira"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3333
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
